### ISSUE TITLE
How to remember the pages data that I have navigated from?

### ISSUE THREAD

**Issue by AliBayatGH** [VahidN/WpfFramework#1]
I need to retain a Page instance in memory, when I navigate by using the Back, Forward ,How can i keep page with full state in navigation ?

**Comment by VahidN** [comment]
Try  setting the [keep alive property](https://msdn.microsoft.com/en-us/library/system.windows.controls.page.keepalive.aspx) of the page.
```xml
<Page x:Class="..." KeepAlive="True">
```

**Comment by AliBayatGH** [comment]
Thanks for your help
What can i do for keep alive viewmodel?

**Comment by VahidN** [comment]
Something like this
```xml
KeepAlive="{Binding DataContext.MyKeepAliveProp, ElementName=TheMainViewName}"
```

**Comment by AliBayatGH** [comment]
Thanks again, but it does not work :(
Data lost from ViewModel when navigating pages.

**Comment by VahidN** [comment]
- If you want just one instance of your view model, mark it as a singleton. use [SingletonConvention](https://github.com/VahidN/WpfFramework/commit/d3762791eac8f8118c215a5c27228d4eacbf66fd) for this scenario.
- Using ViewModels with the [SingletonConvention](https://github.com/VahidN/WpfFramework/commit/d3762791eac8f8118c215a5c27228d4eacbf66fd) is not a good idea. [More info](http://www.dotnettips.info/courses/topic/6/a0efd6b3-b45f-46ab-8f76-77b760148298).

**Comment by AliBayatGH** [comment]
Thanks it worked like a charm.
What would be good if the pages were opened in tabs.
