### ISSUE TITLE
How to navigate forward or back to pages in navigation history?

### ISSUE THREAD

**Issue by AliBayatGH** [VahidN/WpfFramework#2]
We have  switch (_navArgs.NavigationMode) that NavigationMode always is NavigationMode.New, When and How to change NavigationMode to NavigationMode.Back and NavigationMode.Forward?

**Comment by VahidN** [comment]
Change [NavigationUIVisibility="Hidden"](https://github.com/VahidN/WpfFramework/blob/master/MyWpfFramework/MainWindow.xaml#L24) to `Visible` in MainWindow.xaml file to use other modes.
![modes](https://user-images.githubusercontent.com/766010/32428035-0217d694-c2d9-11e7-880a-48260db755f2.png)

**Comment by AliBayatGH** [comment]
You are the best. Thanks for being there.
