### ISSUE TITLE
How to enforce that only a particular user can call a method?

### ISSUE THREAD

**Issue by AliBayatGH** [VahidN/WpfFramework#4]
I have an application, that dealing with many users, I want to restrict functionality according to the authenticated user’s name or role.

I would like to be able to restrict access to a method by demanding that the user belong to a predefined group.
How can i control the access to resources an Application. For example, only certain users should be able to view sensitive data?(like Tabels and DataColumns)
How to create userGroup and assigns it roles?

Thanks. #

**Comment by VahidN** [comment]
You can find the documentation of this project [here](http://www.dotnettips.info/courses/details/6). This questions is discussed there. For instance you can use [PageAuthorization](https://github.com/VahidN/WpfFramework/search?utf8=%E2%9C%93&q=PageAuthorization&type=) attribute to mange the authorization:
```
[PageAuthorization(AuthorizationType.FreeForAuthenticatedUsers)]
public partial class ChangeProfile
```
Or you can use `ApplyRequiredRoles` to restrict a page to a certain group of users:
```
[PageAuthorization(AuthorizationType.ApplyRequiredRoles, "IsAdmin, CanAddNewUser")]
```
Also you can take look its implementation [here](https://github.com/VahidN/WpfFramework/search?utf8=%E2%9C%93&q=PageAuthorizationAttribute&type=).

**Comment by AliBayatGH** [comment]
Great...
but how can i  restrict access to a method ? and how to Hide some datagrid columns to specific users?

"I can't subscribe to dotnettips.info site because I already have a disabled  account"

**Comment by VahidN** [comment]
You can inject the `IAppContextService` interface to your view model's constructor and then use its [IsCurrentUserInRoles](https://github.com/VahidN/WpfFramework/blob/d11f3d1f695d31bfddf63385f2fb37ae3baf9d5f/MyWpfFramework.ServiceLayer/Contracts/IAppContextService.cs#L55) method.

**Comment by AliBayatGH** [comment]
Thanks for your Help
Is there any way an admin user can dynamically give access to program pages(in Run time)?

**Comment by VahidN** [comment]
No. But it's easy to implement. First you need to create a list of the secured pages, by using [PageAuthorizationScanner](https://github.com/VahidN/WpfFramework/search?utf8=%E2%9C%93&q=PageAuthorizationScanner&type=). Then create a table to map these pages to users. And finally update the `AuthorizationType` enum to add `ApplyDynamiRoles` and check it in the [CanCurrentUserNavigateTo](https://github.com/VahidN/WpfFramework/blob/master/MyWpfFramework.ServiceLayer/AppContextService.cs#L150) method.
