### ISSUE TITLE
How to pass data between ViewModels?

### ISSUE THREAD

**Issue by AliBayatGH** [VahidN/WpfFramework#5]
I need to pass an argument from one ViewModel to another, How do I do this in Redirect class?

examples would be most welcome, since I'm newcomer.

**Comment by VahidN** [comment]
follow http://www.dotnettips.info/coursequestion/details/6/28

**Comment by AliBayatGH** [comment]
Thanks for your great article, now I'm clear about how to transfer data between view and viewModels.
I Created a Method like this in Redirect Class

        public static void NavigateTo(string pageName, object arguments)
        {
            Messenger.Default.Send(arguments, "QueryStringData");
            To(pageName);
        }
But _queryString is always null in onNavigated method. :(

how can i resolve this problem?

Thanks in advance!

**Comment by VahidN** [comment]
When you have send in ViewModel A:
```
// Sends a message with a Person object.
var person = new Person { FirstName = "User 1", LastName = "L1" };
Messenger.Default.Send(person);
```

You should have receive or `Register` too in ViewModel B:
``` 
// Registers for incoming Person messages.
Messenger.Default.Register<Person>(this, (person) =>
{
    // Works with the Person object.
});
```

**Comment by AliBayatGH** [comment]
Where to register?
I have to register it in target ViewModel?

**Comment by VahidN** [comment]
Yes. Actually you don't need `NavigateTo`. You can use `Send` and `Register` everywhere (loosely coupled messaging).

**Comment by AliBayatGH** [comment]
So what does Messenger.Default.Register<object>(this, "QueryString", doloadData); in registerMessenger method?

**Comment by AliBayatGH** [comment]
When _queryString  is not null, and Messenger.Default.Send(_queryString, "QueryStringData");  will be executed?

        private void onNavigated(object sender, NavigationEventArgs e)
        {
            //برای ارسال کوئری استرینگ به شکل پیغام مناسب است
            if (_queryString == null) return;
            Messenger.Default.Send(_queryString, "QueryStringData"); //QueryStringData متفاوت است
            _queryString = null;
        }
