### ISSUE TITLE
How to call Messenger.Default.Register before Send?

### ISSUE THREAD

**Issue by AliBayatGH** [VahidN/WpfFramework#6]
I'm having a problem to pass parameters betweeen my ViewModels using the Messenger class

This is the code I'm using :

void doLogin()
{
...
 Redirect.ToWelcomePage();
 Messenger.Default.Send<string>("Hello");
}
--------------------------
in WelcomePageViewModel :

string _s;
    
public WelcomePageViewModel()
{
  Messenger.Default.Register<string>(this, (s) => { _s = s; });
}

In my LoginViewModel (DoLoginCommand), I'm navigating to a WelcomePage and sending a "Hello" as parameter in the Messenger class. 

But in the WelcomePageViewModel constructor, the _s is null .. because i can't call Messenger.Default.Register before Messenger.Default.Send...

I thinks I did something wrong, please help me to resolve this problem.

Thank you.

**Comment by VahidN** [comment]
[How to pass query string data between page](https://github.com/VahidN/WpfFramework/commit/4d05c0b863850544a1d59549d283d10192739823)

**Comment by AliBayatGH** [comment]
I owe you big time.
My gratitude knows no bounds.

**Comment by AliBayatGH** [comment]
I have the same questions as Elham Azadfar  , Please clarify for me 

https://stackoverflow.com/questions/47421477/any-suggestions-or-best-practice-for-exchanage-messages-between-objects-in-mvvm

Could you please respond to these?

**Comment by VahidN** [comment]
Start leaning MVVM [from here](http://www.dotnettips.info/search/label/mvvm#/page/1/date/asc) before starting using this framework.

**Comment by AliBayatGH** [comment]
Thank you very much for this very good and helpful articles! Anyway I have some open questions where I miss some explanation.
Why we need mvvm light messenger, while we can use built in Action and Func delegates?
I need some advice.

**Comment by VahidN** [comment]
`ViewModels` in MVVM are like `Controllers` in MVC and they are not supposed to have direct references to each other.
